const mongoose = require("mongoose");
const db = require("../models");

// This file empties the Books collection and inserts the books below

mongoose.connect(
  process.env.MONGODB_URI ||
  "mongodb://localhost/coasterdb"
);

const coasterSeed = [
  {
    name: "Skyrush",
    park: "Hersheypark",
    location: "Hershey, PA",
    operating: "May 26, 2012",
    type: "Steel",
    manufacturer: "Intamin",
    designer: "Werner Stengel",
    model: "Hyper Coaster",
    height: 212,
    length: 3600,
    drop: 200,
    speed: 75,
    inversions: 0,
    duration: "1:00",
    gforce: "5",
    vertangle: "85°",
    scale: "Extreme",
    awards: "Top 25 Steel Roller Coasters",
    img1: "https://static01.nyt.com/images/2012/06/29/arts/COASTER_SPAN/COASTER-superJumbo.jpg",
    img2: "http://www.familyvacationhub.com/wp-content/uploads/2016/06/skyrush-roller-coaster-hersheypark.jpg",
    img3: "https://media-cdn.tripadvisor.com/media/photo-s/07/63/b7/1b/hersheypark.jpg",
    img4: "https://media-cdn.tripadvisor.com/media/photo-s/12/56/8b/cc/skyrush.jpg",
    date: new Date(Date.now())
  },
  {
    name: "Storm Runner",
    park: "Hersheypark",
    location: "Hershey, PA",
    operating: "May 8, 2004",
    type: "Steel – Launched",
    manufacturer: "Intamin",
    designer: "Werner Stengel",
    model: "Accelerator Coaster",
    height: 150,
    drop: 180,
    length: 2600,
    speed: 72,
    inversions: 3,
    duration: "0:50",
    vertangle: "90°",
    gforce: "5",
    scale: "Extreme",
    awards: "Top 50 Steel Roller Coasters",
    img1: "https://media-cdn.tripadvisor.com/media/photo-s/01/dd/e3/37/storm-runner-0-to-72.jpg",
    img2: "https://www.ultimaterollercoaster.com/coasters/reviews/stormrunner/img/hp_storm_04.jpg",
    img3: "https://i.pinimg.com/originals/72/df/02/72df02304ac25fdaf183428aae238c24.jpg",
    img4: "https://www.ultimaterollercoaster.com/coasters/reviews/stormrunner/img/hp_storm_01.jpg",
    date: new Date(Date.now())
  },
  {
    name: "Sidewinder",
    park: "Hersheypark",
    location: "Hershey, PA",
    operating: "May 11, 1991",
    type: "Steel – Shuttle – Boomerang",
    manufacturer: "Vekoma",
    model: "Boomerang",
    height: 116.5,
    length: 935,
    speed: 47,
    inversions: 6,
    duration: "1:48",
    gforce: "5.2",
    scale: "Extreme",
    img1: "https://live.staticflickr.com/8045/8140342774_826cbef891_b.jpg",
    img2: "https://www.coaster101.com/wp-content/uploads/2017/07/sidewinder-2.jpg",
    img3: "https://i.redd.it/unzh3s8lqaj11.jpg",
    img4: "https://farm1.static.flickr.com/124/417025245_12c54e39d9_b.jpg",
    date: new Date(Date.now())
  },
  {
    name: "Hydra the Revenge",
    park: "Dorney Park",
    location: "Allentown, PA",
    operating: "May 7, 2005",
    type: "Steel – Floorless Coaster",
    manufacturer: "Bolliger & Mabillard",
    designer: "Werner Stengel",
    model: "Floorless Coaster",
    height: 95,
    drop: 105,
    length: 3198,
    speed: 53,
    inversions: 7,
    duration: "2:35",
    vertangle: "68°",
    gforce: "N/A",
    scale: "Extreme",
    awards: "",
    img1: "http://www.heartline-coasters.com/wp-content/uploads/2017/11/Heartline-cover.jpg",
    img2: "https://media-cdn.tripadvisor.com/media/photo-s/01/25/af/05/hydra-the-revenge.jpg",
    img3: "https://coasterbuzz.com/CoasterPhoto/CoasterPhotoImage/3125",
    img4: "https://i.imgur.com/722vL5R.jpg",
    date: new Date(Date.now())
  },
  {
    name: "Possessed",
    park: "Dorney Park",
    location: "Allentown, PA",
    operating: "May 17, 2008",
    type: "Steel – Inverted – Launched",
    manufacturer: "Intamin",
    designer: "Werner Stengel",
    model: "Twisted Impulse Coaster",
    height: 180,
    drop: 125,
    length: 704,
    speed: 70,
    inversions: 0,
    vertangle: "90°",
    gforce: "3.7",
    scale: "Extreme",
    awards: "",
    img1: "https://live.staticflickr.com/7267/7491587004_f490767251_b.jpg",
    img2: "http://www.negative-g.com/dorney-park/2015/dorney-park-2015-posessed-large-2.jpg",
    img3: "http://www.negative-g.com/dorney-park/2015/dorney-park-2015-posessed-large-1.jpg",
    img4: "https://live.staticflickr.com/7266/7491580970_0498d3bd0b_c.jpg",
    date: new Date(Date.now())
  },
  {
    name: "Steel Force",
    park: "Dorney Park",
    location: "Allentown, PA",
    operating: "May 30, 1997",
    type: "Steel – Hypercoaster",
    manufacturer: "D. H. Morgan Manufacturing",
    designer: "Steve Okamoto",
    model: "Hyper Coaster",
    height: 200,
    drop: 205,
    length: 5600,
    speed: 75,
    duration: "3:00",
    vertangle: "61°",
    gforce: "3.4",
    scale: "Extreme",
    awards: "Top 50 Steel Roller Coasters",
    img1: "https://cdn-cloudfront.cfauthx.com/binaries/content/gallery/dp-en-us/blogs/2017/may/sf-blog-post-banner.jpg",
    img2: "https://live.staticflickr.com/91/206588886_b3213bf20c_b.jpg",
    img3: "https://pbs.twimg.com/media/Au9icH9CAAIeghE.jpg",
    img4: "https://i1.wp.com/coastercritic.com/wp-content/uploads/2012/06/T-Rex-and-Steel-Force-Dorney-Park.jpg",
    date: new Date(Date.now())
  },
  {
    name: "Jack Rabbit",
    park: "Kennywood",
    location: "West Mifflin, PA",
    operating: "1920",
    type: "Wood",
    manufacturer: "Harry Baker Coaster",
    designer: "John A. Miller",
    model: "Out and Back roller coaster",
    height: 40,
    drop: 70,
    speed: 45,
    length: 2132,
    inversions: 0,
    vertangle: "45°",
    duration: "1:36",
    scale: "Thrill",
    awards: "ACE Roller Coaster Landmark",
    img1: "https://upload.wikimedia.org/wikipedia/commons/b/b0/Kennywood_Jack_Rabbit_DSCN2775.JPG",
    img2: "https://www.pittsburghmagazine.com/jackrabbit-jun16.jpg",
    img3: "https://www.themeparkreview.com/forum/files/0524.jpg",
    img4: "https://www.themeparkreview.com/forum/files/jackrabbit_-_kennywood_-_2009.07.04_-_18_178.jpg",
    date: new Date(Date.now())
  },
  {
    name: "Racer",
    park: "Kennywood",
    location: "West Mifflin, PA",
    operating: "1927",
    type: "Wood – Racing",
    manufacturer: "Kennywood / John Miller",
    designer: "John A. Miller",
    model: "Racing Mobius Loop",
    height: 72.5,
    drop: 50,
    length: 4500,
    speed: 40,
    inversions: 0,
    duration: "1:32",
    scale: "Thrill",
    awards: "ACE Roller Coaster Landmark",
    img1: "https://upload.wikimedia.org/wikipedia/commons/8/89/KW-Racer.jpg",
    img2: "http://www.negative-g.com/kennywood/2015/kennywood-2015-racer-large-3.jpg",
    img3: "https://www.themeparkreview.com/forum/files/racer1_208.jpg",
    img4: "https://www.thirdstopontheright.com/wp-content/uploads/2019/02/ModernRacer-e1549413269341.jpg",
    date: new Date(Date.now())
  },
  {
    name: "Sky Rocket",
    park: "Kennywood",
    location: "West Mifflin, PA",
    operating: "June 29, 2010",
    type: "Steel",
    manufacturer: "Premier Rides",
    model: "Launch Coaster",
    height: 95,
    length: 2100,
    speed: 50,
    inversions: 3,
    duration: "1:05",
    vertangle: "90°",
    gforce: "0.8",
    scale: "Extreme",
    awards: ["Top Steel Roller Coasters", "Best New Ride for 2010"],
    img1: "https://www.kennywood.com/sites/kennywood.com/files/kennywood_SkyRocket7.jpg",
    img2: "https://www.kennywood.com/sites/kennywood.com/files/kennywood_SkyRocket8.jpg",
    img3: "https://www.kennywood.com/sites/kennywood.com/files/kennywood_SkyRocket3.jpg",
    img4: "https://www.kennywood.com/sites/kennywood.com/files/kennywood_SkyRocket4.jpg",
    date: new Date(Date.now())
  },
  {
    name: "Steel Curtain",
    park: "Kennywood",
    location: "West Mifflin, PA",
    operating: "Summer 2019",
    type: "Steel",
    manufacturer: "S&S - Sansei Technologies",
    designer: "Joe Draves",
    height: 220,
    length: 4000,
    speed: 76,
    inversions: 9,
    duration: "2:00",
    vertangle: "90°",
    gforce: "N/A",
    scale: "Extreme",
    img1: "https://cdn.vox-cdn.com/thumbor/KNL6gQfXKwJdyNnl94tEwmQ4N4w=/0x0:6830x3530/1200x800/filters:focal(2390x1254:3482x2346)/cdn.vox-cdn.com/uploads/chorus_image/image/60446805/Steel_Curtain_full_coaster_2.0.png",
    img2: "https://i.ytimg.com/vi/CbsNYPm3pMU/maxresdefault.jpg",
    img3: "https://www.kennywood.com/sites/kennywood.com/files/GBP_4095%2020181102%200837%20S%26S%20Steeler%20Coaster_HDR.jpg",
    img4: "https://www.kennywood.com/sites/kennywood.com/files/GBP_4158%2020181102%200847%20S%26S%20Steeler%20Coaster_HDR.jpg",
    date: new Date(Date.now())
  },
  {
    name: "Black Diamond",
    park: "Knoebels Amusement Park & Resort",
    location: "Elysburg, PA",
    operating: "October 8, 2011",
    type: "Steel",
    manufacturer: "Philadelphia Toboggan Coasters",
    designer: "John C. Allen",
    model: "Enclosed",
    height: 35,
    speed: 12,
    inversions: 0,
    scale: "Family",
    date: new Date(Date.now())

  },
  {
    name: "Blue Streak",
    park: "Conneaut Lake Park",
    location: "Conneaut Lake, PA",
    operating: "May 23, 1938",
    type: "Wood",
    designer: "Ed Vettel",
    model: "Out and Back",
    height: 78,
    length: 2900,
    speed: 50,
    inversions: 0,
    duration: "2:20",
    date: new Date(Date.now())

  },
  {
    name: "Comet",
    park: "Hersheypark",
    location: "Hershey, PA",
    operating: "May 30, 1946",
    type: "Wood",
    manufacturer: "Philadelphia Toboggan Coasters",
    designer: "Herbert Paul Schmeck",
    model: "Modified Double Out and Back",
    vertangle: "47°",
    length: 3360,
    height: 84,
    drop: 78,
    speed: 50,
    inversions: 0,
    duration: "1:45",
    scale: "Extreme",
    date: new Date(Date.now())


  },
  {
    name: "Cocoa Cruiser",
    park: "Hersheypark",
    location: "Hershey, PA",
    type: "Steel",
    manufacturer: "Zamperla",
    model: "Family Gravity Coaster",
    height: 14,
    length: 279,
    speed: 16,
    duration: "0:45",
    inversions: 0,
    scale: "Family",
    date: new Date(Date.now())

  },
  {
    name: "Comet",
    park: "Waldameer Park",
    location: "Erie, PA",
    operating: "1951",
    type: "Wood",
    manufacturer: "Philadelphia Toboggan Coasters",
    designer: "Herbert Paul Schmeck",
    model: "Wood",
    height: 37,
    drop: 25,
    length: 1300,
    speed: 25,
    inversions: 0,
    duration: "1:24",
    scale: "Family",
    awards: "ACE Roller Coaster Classic",
    date: new Date(Date.now())

  },
  {
    name: "Crazy Mouse",
    park: "DelGrosso's Amusement Park",
    location: "Tipton, PA",
    operating: "2004",
    manufacturer: "Reverchon",
    model: "Spinning Coaster",
    length: 1378,
    height: 42.7,
    speed: 29.1,
    inversions: 0,
    duration: "1:30",
    gforce: 2.5,
    scale: "Thrill",
    date: new Date(Date.now())


  },
  {
    name: "Devil's Den",
    park: "Conneaut Lake Park",
    location: "Conneaut Lake, PA",
    operating: "1968",
    type: "Wood",
    manufacturer: "Pretzel Amusement Ride Company",
    model: "Gravity Pretzel - Dark Ride",
    height: 20,
    speed: 10,
    inversions: 0,
    duration: "1:40",
    scale: "Family",
    date: new Date(Date.now())

  },
  {
    name: "Exterminator",
    park: "Kennywood",
    location: "West Mifflin, PA",
    operating: "April 18, 1999",
    type: "Steel – Enclosed – Spinning",
    manufacturer: "Reverchon Industries",
    designer: "Reverchon Industries",
    model: "Spinning Coaster",
    height: 42.7,
    length: 1377.9,
    speed: 29.1,
    inversions: 0,
    duration: "1:48",
    gforce: 2.5,
    scale: "Thrill",
    date: new Date(Date.now())

  },
  {
    name: "Fahrenheit",
    park: "Hersheypark",
    location: "Hershey, PA",
    operating: "May 24 2008",
    type: "Steel",
    manufacturer: "Intamin",
    height: 121,
    length: 2700,
    speed: 58,
    inversions: 6,
    duration: "1:25",
    vertangle: "97°",
    gforce: 5,
    scale: "Extreme",
    img1: "https://www.themeparkinsider.com/photos/images/fahrenheit1.jpg",
    img2: "https://media-cdn.tripadvisor.com/media/photo-s/04/70/93/9a/fahrenheit-hershey-park.jpg",
    img3: "https://i2.wp.com/www.coastercritic.com/wp-content/uploads/2011/01/fahrenheit19-track.jpg_920.jpg",
    img4: "https://i.redd.it/w2cro1tgpjn21.jpg",
    date: new Date(Date.now())

  },
  {
    name: "Fiesta Express",
    park: "Fun Fore All Family Entertainment Center",
    location: "Cranberry Township, PA",
    operating: "August 2003",
    type: "Steel",
    manufacturer: "Zamperla",
    model: "Wild Mouse / Mini Mouse",
    length: 262,
    height: 8,
    inversions: "0",
    scale: "Family",
    date: new Date(Date.now())

  },
  {
    name: "Flying Turns",
    park: "Knoebels Amusement Resort",
    location: "Elysburg, PA",
    operating: "October 5, 2013",
    type: "Wood – Bobsled",
    manufacturer: "Knoebels Amusement Resort",
    designer: "John Fetterman",
    height: 50,
    length: 1300,
    speed: 24,
    inversions: "0",
    scale: "Thrill",
    img1: "https://www.themeparkreview.com/forum/files/ppp06034_880.jpg",
    img2: "https://www.latimes.com/resizer/yIWfldFYE5d88cs2TGBy7FIwPNc=/800x0/arc-anglerfish-arc2-prod-tronc.s3.amazonaws.com/public/PWPWFOTH7JAX7A2YPF6OY6UYCY.jpg",
    img3: "http://rollercoastermuseum.org/wp-content/uploads/2017/11/Knoebels-Opens-Flying-Turns_Feature-1080x675.jpg",
    img4: "http://www.themeparkguide.org/wp-content/uploads/2013/11/flyingturns.jpg",
    date: new Date(Date.now())

  },
  {
    name: "Great Bear",
    park: "Hersheypark",
    location: "Hershey, PA",
    operating: "May 23, 1998",
    type: "Steel – Inverted",
    manufacturer: "Bolliger & Mabillard",
    designer: "Werner Stengel",
    model: "Inverted Coaster",
    height: 90,
    drop: 124,
    length: 2800,
    speed: 58,
    inversions: 4,
    duration: "2:55",
    scale: "Extreme",
    img1: "https://images.fineartamerica.com/images-medium-large-5/hershey-park-great-bear-roller-coaster-121213-dc-photographer.jpg",
    img2: "https://coasterbuzz.com/CoasterPhoto/CoasterPhotoImage/1921",
    img3: "http://thedod3.com/wp-content/uploads/2013/06/greatbear3a.jpg",
    img4: "https://www.themeparkreview.com/pa2004/hp/hershey10.jpg",

    date: new Date(Date.now())

  },
  {
    name: "Impulse",
    park: "Knoebels Amusement Resort",
    location: "Elysburg, PA",
    operating: "April 25, 2015",
    type: "Steel",
    manufacturer: "Zierer",
    model: "Tower Speed Coaster",
    height: 98,
    speed: 55,
    inversions: 4,
    duration: "1:10",
    vertangle: "90°",
    gforce: 4.2,
    scale: "Extreme",
    img1: "https://www.pennlive.com/resizer/OySzUc3CJg3HsNp3ifrlsun8_Sg=/1200x0/advancelocal-adapter-image-uploads.s3.amazonaws.com/image.pennlive.com/home/penn-media/width2048/img/midstate_impact/photo/impulse-steel-46d03032d2026859.jpg",
    img2: "https://www.themeparkinsider.com/photos/images/Impulse1CB.JPG",
    img3: "https://media-cdn.tripadvisor.com/media/photo-s/0b/d9/5e/f0/impulse-this-is-a-new.jpg",
    img4: "https://www.themeparkreview.com/upd_images/1425068286_1.jpg",
    date: new Date(Date.now())
  },
  {
    name: "Joust",
    park: "Dutch Wonderland",
    location: "Lancaster, PA",
    operating: "5/23/1998",
    manufacturer: "Chance Rides",
    model: "Big Dipper",
    height: 16.1,
    inversions: 0,
    speed: 15,
    scale: "Family",
    date: new Date(Date.now())
  },
  {
    name: "Kingdom Coaster",
    park: "Dutch Wonderland",
    location: "Lancaster, PA",
    operating: "1992",
    type: "Wood – Family",
    manufacturer: "Custom Coasters International",
    height: 55,
    length: 2200,
    speed: 40,
    duration: "1:30",
    scale: "Thrill",
    date: new Date(Date.now())

  },
  {
    name: "Kozmo's Kurves",
    park: "Knoebels Amusement Resort",
    location: "Elysburg, PA",
    operating: "August 1, 2009",
    type: "Steel – Junior",
    manufacturer: "E&F Miler Industries",
    model: "Family Coaster",
    height: 17,
    speed: 30,
    inversions: 0,
    duration: "1:17",
    scale: "Family",
    date: new Date(Date.now())

  },
  {
    name: "Leap-The-Dips",
    park: "Lakemont Park",
    location: "Altoona, PA",
    operating: "1902",
    type: "Wood – Side friction",
    model: "Figure 8",
    manufacturer: "Federal Construction Company",
    designer: "Edward Joy Morris",
    height: 41,
    drop: 9,
    length: 1452,
    speed: 10,
    duration: "1:00",
    vertangle: "25°",
    scale: "Thrill",
    awards: ["Oldest Roller Coaster in the World", "ACE Roller Coaster Landmark Award", "ACE Roller Coaster Classic Award"],
    img1:"https://upload.wikimedia.org/wikipedia/commons/d/d2/Leap_The_Dips_%28Lakemont_Park%29.jpg",
    img2: "https://ghosty-production.s3.amazonaws.com/fotospot_spots/Oldest-Roller-Coaster-in-America-Fotospot_27137c7a8787093129ebf6c9563258eb/large.jpg",
    img3: "https://timenewsfeed.files.wordpress.com/2013/06/leap-the-dips1.jpg?w=720&h=480&crop=1",
    img4: "https://i.pinimg.com/originals/5a/b4/31/5ab431f4db43213ec25f0f2bc44305ef.jpg",
    date: new Date(Date.now())

  },
  {
    name: "Laff Trakk",
    park: "Hersheypark",
    location: "Hershey, PA",
    operating: "May 23, 2015",
    type: "Steel",
    manufacturer: "Maurer Söhne",
    model: "Indoor-Spinning Glow",
    height: 51,
    length: 1400,
    speed: 40,
    inversions: 0,
    duration: "1:10",
    scale: "Thrill",
    date: new Date(Date.now())

  },
  {
    name: "Lightning Racer",
    park: "Hersheypark",
    location: "Hershey, PA",
    operating: "May 13, 2000",
    type: "Wood",
    manufacturer: "Great Coasters International",
    model: "Racing roller coaster",
    height: 92,
    drop: 90,
    length: 3393,
    speed: 51,
    inversions: 0,
    duration: "2:20",
    vertangle: "45°",
    gforce: 3.6,
    scale: "Extreme",
    img1: "https://greatcoasters.com/images/uploaded/2c19b31727_full.jpg",
    img2: "https://greatcoasters.com/images/uploaded/ce85264470_full.jpg",
    img3: "https://media-cdn.tripadvisor.com/media/photo-s/0d/03/b9/d7/lightning-racer.jpg",
    img4: "https://greatcoasters.com/images/uploaded/75d30d0d67_full.jpg",
    date: new Date(Date.now())

  },
  {
    name: "Lil' Phantom",
    park: "Kennywood",
    location: "West Mifflin, PA",
    operating: "1996",
    manufacturer: "Molina & Son's",
    model: "Moli-Coaster (Low Park Model)",
    drop: 6,
    height: 7,
    length: 154,
    duration: "0:30",
    speed: 15,
    scale: "Kiddie",
    date: new Date(Date.now())

  },
  {
    name: "Little Dipper",
    park: "Conneaut Lake Park",
    location: "Conneaut Lake, PA",
    operating: "1950",
    type: "Steel",
    manufacturer: "Allan Herschell Company",
    model: "Little Dipper",
    height: 10,
    speed: 15,
    duration: "0:40",
    inversions: 0,
    scale: "Kiddie",
    date: new Date(Date.now())

  },
  {
    name: "Little Leaper",
    park: "Lakemont Park",
    location: "Altoona, PA",
    operating: "1991",
    type: "Steel",
    manufacturer: "Allan Herschell Company",
    designer: "Bradley and Kaye",
    model: "Little Dipper",
    inversions: 0,
    height: 10,
    speed: 15,
    duration: "0:40",
    scale: "Kiddie",
    date: new Date(Date.now())


  },
  {
    name: "Merlin's Mayhem",
    park: "Dutch Wonderland",
    location: "Lancaster, PA",
    operating: "4/28/2018",
    type: "Steel",
    model: "Inverted",
    manufacturer: "S&S Sansei Technologies",
    designer: "Joe Draves",
    length: 1300,
    height: 60,
    speed: 45,
    inversions: 0,
    duration: "0:45",
    scale: "Family",
    date: new Date(Date.now())

  },
  {
    name: "Appalachian Express Mountain Coaster",
    park: "Camelback Mountain Adventures",
    location: "Tannersville, PA",
    operating: "2012",
    type: "Steel",
    manufacturer: "Aquatic Development Group",
    model: "Mountain Coaster",
    length: 4500,
    speed: 27,
    height: 300,
    duration: "2:40",
    date: new Date(Date.now())

  },
  {
    name: "Oscar's Wacky Taxi",
    park: "Sesame Place",
    location: "Langhorne, PA",
    operating: "5/26/2018",
    type: "Wood",
    manufacturer: "Gravitykraft Corporation",
    length: 1205,
    height: 43,
    drop: 39,
    speed: 34,
    inversions: 0,
    vertangle: "50°",
    scale: "Family",
    img1: "https://www.themeparkreview.com/parks/pimages/Sesame_Place/Oscars_Wacky_Taxi/20180602_174613.jpg",
    img2: "https://d302e0npexowb4.cloudfront.net/wp-content/uploads/2018/08/19094343/Oscars-Wacky-Taxi-Sesame-Place-US-roller-coasters-2018..jpg",
    img3: "https://live.staticflickr.com/1855/43596549694_5666c0c9f2_b.jpg",
    img4: "https://i.pinimg.com/736x/64/68/92/6468928c59ce09dc6154cf9038528570.jpg",
    date: new Date(Date.now())

  },
  {
    name: "Phantom's Revenge",
    park: "Kennywood",
    location: "West Mifflin, PA",
    operating: "May 10, 1991",
    type: "Steel",
    manufacturer: "Arrow Dynamics/Morgan Manufacturing",
    designer: "Harry Henninger",
    model: "Mega Coaster",
    height: 160,
    drop: 232,
    length: 3365,
    speed: 85,
    inversions: 0,
    duration: "1:45",
    vertangle: "52°",
    gforce: 3.5,
    scale: "Extreme",
    img1: "https://i2.wp.com/www.wblzmedia.com/wp-content/uploads/2017/09/PIC44976.jpg",
    img2: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Demon_Roller_Coaster.jpg/1200px-Demon_Roller_Coaster.jpg",
    img3: "https://radioimg.s3.amazonaws.com/kdkaam/Phantom%27s%20Revenge%20-%20Thunderbolt%20-%20Jonathan%20Plum.jpg",
    img4: "https://media-cdn.tripadvisor.com/media/photo-s/13/47/12/d1/phantom-s-revenge.jpg",
    date: new Date(Date.now())

  },
  {
    name: "Phoenix",
    park: "Knoebels Amusement Park & Resort",
    location: "Elysburg, PA",
    operating: "6/15/1985",
    type: "Wood",
    manufacturer: "Philadelphia Toboggan Coasters",
    designer: "Herbert Paul Schmeck, 1947",
    model: "Double Out and Back",
    height: 78,
    drop: 72,
    length: 3200,
    speed: 45,
    inversions: 0,
    duration: "2:00",
    scale: "Thrill",
    date: new Date(Date.now())

  },
  {
    name: "Ravine Flyer 3",
    park: "Waldameer",
    location: "Erie, PA",
    operating: "2000",
    manufacturer: "E&F Miler Industries",
    type: "Steel",
    height: 13,
    drop: 13,
    speed: 15,
    length: 330,
    inversions: 0,
    duration: "0:50",
    scale: "Family",
    date: new Date(Date.now())

  },
  {
    name: "Ravine Flyer II",
    park: "Waldameer",
    location: "Erie, PA",
    operating: "May 17, 2008",
    type: "Wood",
    manufacturer: "The Gravity Group",
    designer: "The Gravity Group",
    height: 85,
    drop: 120,
    length: 2900,
    speed: 60,
    inversions: 0,
    duration: "1:30",
    vertangle: "60°",
    gforce: 3.5,
    scale: "Extreme",
    img1: "https://i.ytimg.com/vi/pDn671vEKxk/maxresdefault.jpg",
    img2: "https://www.themeparkreview.com/forum/files/ravine18_149.jpg",
    img3: "https://i.pinimg.com/originals/93/a8/a4/93a8a46478c75ec0c19c3dcc20a64c30.jpg",
    img4: "https://www.themeparkreview.com/parks/pimages/Waldameer_Amusement_Park/Ravine_Flyer_II_Film_Shoot/ravineflyer2_130.jpg",
    date: new Date(Date.now())

  },
  {
    name: "Rollo Coaster",
    park: "Idlewild & SoakZone",
    location: "Ligonier, PA",
    operating: "1938",
    type: "Wood",
    manufacturer: "Philadelphia Toboggan Coasters",
    designer: "Herbert Paul Schmeck",
    model: "Out and Back",
    length: 900,
    height: 27,
    drop: 25,
    speed: 25,
    duration: "1:15",
    inversions: 0,
    scale: "Family",
    awards: "ACE Coaster Classic",
    date: new Date(Date.now())

  },
  {
    name: "SooperDooperLooper",
    park: "Hersheypark",
    location: "Hershey, PA",
    operating: "July 4, 1977",
    type: "Steel",
    manufacturer: "Anton Schwarzkopf",
    designer: "Werner Stengel",
    model: "Terrain Coaster",
    height: 75,
    drop: 70,
    length: 2614,
    speed: 45,
    inversions: 1,
    duration: "1:45",
    scale: "Extreme",
    img1: "https://coasterbuzz.com/CoasterPhoto/CoasterPhotoImage/7704",
    img2: "https://media-cdn.tripadvisor.com/media/photo-s/12/56/8b/cf/sooperdooperlooper.jpg",
    img3: "https://i1.wp.com/www.coastercritic.com/wp-content/uploads/2018/01/image-1024x768.jpeg?resize=730%2C548",
    img4: "https://i0.wp.com/www.coastercritic.com/wp-content/uploads/2018/01/image-4-1024x768.jpeg?resize=730%2C548",
    date: new Date(Date.now())

  },
  {
    name: "Steel Dragon",
    park: "Waldameer",
    location: "Erie, PA",
    operating: "July 2, 2004",
    type: "Steel",
    manufacturer: "Maurer Söhne",
    model: "Spinning Coaster",
    height: 51,
    length: 1391,
    speed: 37.3,
    inversions: 0,
    duration: "1:24",
    vertangle: "50°",
    scale: "Thrill",
    date: new Date(Date.now())

  },
  {
    name: "Talon: The Grip of Fear",
    park: "Dorney Park & Wildwater Kingdom",
    location: "Allentown, PA",
    operating: "May 5, 2001",
    type: "Steel",
    manufacturer: "Bolliger & Mabillard",
    designer: "Werner Stengel",
    model: "Inverted Coaster",
    height: 135,
    drop: 120,
    length: 3110,
    speed: 58,
    inversions: 4,
    duration: "2:00",
    vertangle: "50°",
    gforce: 4.5,
    scale: "Extreme",
    awards: "Golden Ticket Top 25 Steel Roller Coasters",
    img1: "http://www.ridezone.com/rides/coasters/talon/talon20010588/20010514-30.jpg",
    img2: "https://pennwatch.org/wp-content/uploads/2018/12/DorneyPark_gallery2_75e2a867-5056-a36a-07d65858c159f365.jpg",
    img3: "https://i.imgur.com/cSKFoG2.jpg",
    img4: "https://www.themeparkreview.com/pa2004/dp/dpj02.jpg",
    date: new Date(Date.now())

  },
  {
    name: "Thunderbolt",
    park: "Kennywood",
    location: "West Mifflin, PA",
    operating: 1924,
    type: "Wood",
    manufacturer: "Andy Vettel",
    designer: "Andy Vettel & John A. Miller",
    height: 70,
    drop: 90,
    length: 3250,
    speed: 55,
    inversions: 0,
    duration: "1:41",
    scale: "Extreme",
    img1: "https://patch.com/img/cdn20/users/22920172/20180816/092203/styles/raw/public/processed_images/tbolt1-1524255747-434-1534425481-9646.jpg",
    img2: "https://i.ytimg.com/vi/IeSeJfERJH4/hqdefault.jpg",
    img3: "https://www.themeparkreview.com/forum/files/thunderbolt2_720.jpg",
    img4: "https://www.coaster101.com/wp-content/uploads/2017/06/DSC06564.jpg",
    awards: ["ACE Coaster Classic and Coaster Landmark", "Golden Ticket Top 10 Wood Roller Coasters"],
    date: new Date(Date.now())


  },
  {
    name: "Thunderhawk",
    park: "Dorney Park & Wildwater Kingdom",
    location: "Allentown, PA",
    operating: "May 18, 1923",
    type: "Wood",
    manufacturer: "Philadelphia Toboggan Coasters",
    designer: "Herbert Paul Schmeck",
    model: "Figure 8",
    height: 80,
    drop: 65,
    length: 2767,
    speed: 45,
    inversions: 0,
    duration: "1:18",
    vertangle: "45°",
    scale: "Thrill",
    date: new Date(Date.now())
  },
  {
    name: "Trailblazer",
    park: "Hersheypark",
    location: "Hershey, PA",
    operating: "May 14 1974",
    type: "Steel",
    manufacturer: "Arrow Development",
    model: "Mine train",
    height: 43,
    length: 1600,
    speed: 35,
    inversions: 0,
    duration: "1:15",
    scale: "Thrill",
    date: new Date(Date.now())

  },
  {
    name: "Twister",
    park: "Knoebels Amusement Resort",
    location: " Elysburg, PA",
    operating: "July 24, 1999",
    type: "Wood",
    manufacturer: "Knoebels Amusement Resort",
    designer: "John Fetterman",
    model: "John Allen's 1964 Mister Twister design",
    height: 101.5,
    drop: 89.6,
    length: 3900,
    speed: 51,
    inversions: 0,
    duration: "2:10",
    scale: "Extreme",
    img1: "https://www.themeparkreview.com/parks/pimages/Knoebels_Amusement_Park_&_Resort/USA_2016_-_Robb_&_Elissa_Traveling_Around_Riding_Stuff/Co93c_iXEAAq7nZ.jpg",
    img2: "https://i.ytimg.com/vi/g904pqr3ipQ/maxresdefault.jpg",
    img3: "https://i.redd.it/k4wj6ijyb8v21.jpg",
    img4: "https://media-cdn.tripadvisor.com/media/photo-s/08/41/33/0f/knoebels-amusement-resort.jpg",
    awards: "Golden Ticket Top 25 Wood Roller Coasters",
    date: new Date(Date.now())

  },
  {
    name: "Vapor Trail",
    park: "Sesame Place",
    location: "Langhorne, PA",
    operating: "June 1998",
    type: "Steel",
    manufacturer: "Vekoma",
    model: "Junior Coaster",
    height: 43,
    drop: 56,
    length: 1300,
    speed: 27,
    inversions: 0,
    duration: "1:15",
    scale: "Family",
    date: new Date(Date.now())


  },
  {
    name: "Wacky Worm",
    park: "DelGrosso's Amusement Park",
    location: "Tipton, PA",
    operating: "2004",
    type: "Steel",
    manufacturer: "Fajume",
    model: "Wacky Worm",
    inversions: 0,
    height: 15,
    drop: 8,
    speed: 15,
    length: 330,
    inversions: 0,
    duration: "0:45",
    scale: "Family",
    date: new Date(Date.now())


  },
  {
    name: "Wildcat",
    park: "Hersheypark",
    location: "Hershey, PA",
    operating: "May 26, 1996",
    type: "Wood",
    manufacturer: "Great Coasters International",
    designer: "Mike Boodley",
    height: 106,
    drop: 85,
    length: 3183,
    speed: 50,
    gforce: 3.5,
    duration: "1:15",
    scale: "Extreme",
    img1: "http://www.greatcoasters.com/images/uploaded/1858750b1d_full.jpg",
    img2: "https://www.themeparkreview.com/pa2004/hp/hersheyj14.jpg",
    img3: "https://www.themeparkreview.com/forum/files/hp_13_146.jpg",
    img4: "https://sgmstimberwolftimes.com/wp-content/uploads/2014/09/hersheypark.jpg",
    awards: "Golden Ticket Top 25 Wood Roller Coasters",
    date: new Date(Date.now())

  },
  {
    name: "Wild Mouse",
    park: "Idlewild and Soak Zone",
    location: "Ligonier, PA",
    operating: "1985",
    type: "Steel",
    manufacturer: "Vekoma",
    designer: "Ingenieurbüro Stengel GmbH",
    model: "Wild mouse",
    height: 56,
    length: 1640,
    speed: 30,
    duration: "2:00",
    inversions: 0,
    scale: "Thrill",
    date: new Date(Date.now())

  },
  {
    name: "Wild Mouse",
    park: "Hersheypark",
    location: "Hershey, PA",
    operating: "May 8, 1999",
    type: "Steel",
    manufacturer: "Mack Rides",
    designer: "Ingenieurbüro Stengel GmbH",
    model: "Compact Wild Mouse",
    height: 45,
    length: 1213,
    speed: 28,
    duration: "1:58",
    inversions: 0,
    scale: "Thrill",
    date: new Date(Date.now())

  },
  {
    name: "Wild Mouse",
    park: "Dorney Park & Wildwater Kingdom",
    location: "Allentown, PA",
    operating: " 2000",
    type: "Steel",
    manufacturer: "Maurer Rides GmbH",
    model: "Wild Maus Classic / Right",
    designer: "Ingenieurbüro Stengel GmbH",
    length: 1213.9,
    height: 49.3,
    speed: 28,
    inversions: 0,
    vertangle: "	46°",
    duration: "1:10",
    scale: "Thrill",
    date: new Date(Date.now())

  },
  {
    name: "Woodstock Express",
    park: "Dorney Park & Wildwater Kingdom",
    location: "Allentown, PA",
    operating: "2000",
    type: "Steel",
    manufacturer: "Zamperla",
    model: "Family Gravity Coaster",
    height: 13,
    drop: 8,
    length: 262.6,
    speed: 13,
    inversions: 0,
    duration: "1:00",
    scale: "Family",
    date: new Date(Date.now())

  }
];

db.Coaster
  .remove({})
  .then(() => db.Coaster.collection.insertMany(coasterSeed))
  .then(data => {
    console.log(data.result.n + " records inserted!");
    process.exit(0);
  })
  .catch(err => {
    console.error(err);
    process.exit(1);
  });
