const mongoose = require("mongoose");
const db = require("../models");

// This file empties the Books collection and inserts the books below

mongoose.connect(
  process.env.MONGODB_URI ||
  "mongodb://localhost/coasterdb"
);

const coasterSeed = [
  {
    name: "Skyrush",
    park: "Hersheypark",
    location: "Hershey, PA",
    operating: "May 26, 2012",
    type: "Steel",
    manufacturer: "Intamin",
    designer: "Werner Stengel",
    model: "Hyper Coaster",
    height: 212,
    length: 3600,
    drop: 200,
    speed: 75,
    inversions: 0,
    duration: "1:00",
    gforce: "5",
    vertangle: "85",
    scale: "Extreme",
    awards: "Top 50 Steel Roller Coasters",
    img1: "https://static01.nyt.com/images/2012/06/29/arts/COASTER_SPAN/COASTER-superJumbo.jpg",
    img2: "http://www.familyvacationhub.com/wp-content/uploads/2016/06/skyrush-roller-coaster-hersheypark.jpg",
    img3: "https://media-cdn.tripadvisor.com/media/photo-s/07/63/b7/1b/hersheypark.jpg",
    img4: "https://media-cdn.tripadvisor.com/media/photo-s/12/56/8b/cc/skyrush.jpg",
    date: new Date(Date.now())
  },
  {
    name: "Storm Runner",
    park: "Hersheypark",
    location: "Hershey, PA",
    operating: "May 8, 2004",
    type: "Steel – Launched",
    manufacturer: "Intamin",
    designer: "Werner Stengel",
    model:	"Accelerator Coaster",
    height: 150,
    drop: 180,
    length: 2600,
    speed: 72,
    inversions: 3,
    duration: "0:50",
    vertangle: "90",
    gforce: "5",
    scale: "Extreme",
    awards: "Top 50 Steel Roller Coasters",
    img1: "https://media-cdn.tripadvisor.com/media/photo-s/01/dd/e3/37/storm-runner-0-to-72.jpg",
    img2: "https://www.ultimaterollercoaster.com/coasters/reviews/stormrunner/img/hp_storm_04.jpg",
    img3: "https://i.pinimg.com/originals/72/df/02/72df02304ac25fdaf183428aae238c24.jpg",
    img4: "https://www.ultimaterollercoaster.com/coasters/reviews/stormrunner/img/hp_storm_01.jpg",
    date: new Date(Date.now())
  },
  {
    name: "Sidewinder",
    park: "Hersheypark",
    location: "Hershey, PA",
    operating: "May 11, 1991",
    type: "Steel – Shuttle – Boomerang",
    manufacturer: "Vekoma",
    model: "Boomerang",
    height: 116.5,
    length: 935,
    speed: 47,
    inversions: 6,
    duration: "1:48",
    gforce: "5.2",
    vertangle: "N/A",
    scale: "Extreme",
    awards: "",
    img1: "https://live.staticflickr.com/8045/8140342774_826cbef891_b.jpg",
    img2: "https://www.coaster101.com/wp-content/uploads/2017/07/sidewinder-2.jpg",
    img3: "https://i.redd.it/unzh3s8lqaj11.jpg",
    img4: "https://farm1.static.flickr.com/124/417025245_12c54e39d9_b.jpg",
    date: new Date(Date.now())
  },
  {
    name: "Hydra the Revenge",
    park: "Dorney Park",
    location: "Allentown, PA",
    operating: "May 7, 2005",
    type: "Steel – Floorless Coaster",
    manufacturer: "Bolliger & Mabillard",
    designer: "Werner Stengel",
    model: "Floorless Coaster",
    height: 95,
    drop: 105,
    length: 3198,
    speed: 53,
    inversions: 7,
    duration: "2:35",
    vertangle: "68",
    gforce: "N/A",
    scale: "Extreme",
    awards: "",
    img1: "http://www.heartline-coasters.com/wp-content/uploads/2017/11/Heartline-cover.jpg",
    img2: "https://media-cdn.tripadvisor.com/media/photo-s/01/25/af/05/hydra-the-revenge.jpg",
    img3: "https://coasterbuzz.com/CoasterPhoto/CoasterPhotoImage/3125",
    img4: "https://i.imgur.com/722vL5R.jpg",
    date: new Date(Date.now())
  },
  {
    name: "Possessed",
    park: "Dorney Park",
    location: "Allentown, PA",
    operating: "May 17, 2008",
    type: "Steel – Inverted – Launched",
    manufacturer: "Intamin",
    designer: "Werner Stengel",
    model: "Twisted Impulse Coaster",
    height: 180,
    drop: 125,
    length: 704,
    speed: 70,
    inversions: 0,
    vertangle: "90",
    gforce: "3.7",
    scale: "Extreme",
    awards: "",    
    img1: "https://live.staticflickr.com/7267/7491587004_f490767251_b.jpg",
    img2: "http://www.negative-g.com/dorney-park/2015/dorney-park-2015-posessed-large-2.jpg",
    img3: "http://www.negative-g.com/dorney-park/2015/dorney-park-2015-posessed-large-1.jpg",
    img4: "https://live.staticflickr.com/7266/7491580970_0498d3bd0b_c.jpg",
    date: new Date(Date.now())
  },
  {
    name: "Steel Force",
    park: "Dorney Park",
    location: "Allentown, PA",
    operating: "May 30, 1997",
    type: "Steel – Hypercoaster",
    manufacturer: "D. H. Morgan Manufacturing",
    designer: "Steve Okamoto",
    model: "Hyper Coaster",
    height: 200,
    drop: 205,
    length: 5600,
    speed: 75,
    duration: "3:00",
    vertangle: "61",
    gforce: "3.4",
    scale: "Extreme",
    awards: "Top 50 Steel Roller Coasters",
    img1: "https://cdn-cloudfront.cfauthx.com/binaries/content/gallery/dp-en-us/blogs/2017/may/sf-blog-post-banner.jpg",
    img2: "https://live.staticflickr.com/91/206588886_b3213bf20c_b.jpg",
    img3: "https://pbs.twimg.com/media/Au9icH9CAAIeghE.jpg",
    img4: "https://i.pinimg.com/originals/02/7d/3c/027d3ce8a47f3b6d07af14525bce5911.jpg",
    date: new Date(Date.now())
  },
  {
    name: "Jack Rabbit",
    park: "Kennywood",
    location: "West Mifflin, PA",
    operating: "1920",
    type: "Wood",
    manufacturer: "Harry Baker Coaster",
    designer: "John A. Miller",
    model: "Out and Back roller coaster",
    height: 40,
    drop: 70,
    speed: 45,
    length: 2132,
    inversions: 0,
    vertangle: "45",
    duration: "1:36",
    gforce: "N/A",
    scale: "Thrill",
    awards: "ACE Roller Coaster Landmark",
    img1: "https://upload.wikimedia.org/wikipedia/commons/b/b0/Kennywood_Jack_Rabbit_DSCN2775.JPG",
    img2: "https://www.pittsburghmagazine.com/jackrabbit-jun16.jpg",
    img3: "https://www.themeparkreview.com/forum/files/0524.jpg",
    img4: "https://www.themeparkreview.com/forum/files/jackrabbit_-_kennywood_-_2009.07.04_-_18_178.jpg",
    date: new Date(Date.now())
  },
  {
    name: "Racer",
    park: "Kennywood",
    location: "West Mifflin, PA",
    operating: "1927",
    type: "Wood – Racing",
    manufacturer: "Kennywood / John Miller",
    designer: "John A. Miller",
    model: "Racing Mobius Loop",
    height: 72.5,
    drop: 50,
    length: 4500,
    speed: 40,
    inversions: 0,
    duration: "1:32",
    gforce: "N/A",
    vertangle: "N/A",
    scale: "Thrill",
    awards: "ACE Roller Coaster Landmark",
    img1: "https://upload.wikimedia.org/wikipedia/commons/8/89/KW-Racer.jpg",
    img2: "http://www.negative-g.com/kennywood/2015/kennywood-2015-racer-large-3.jpg",
    img3: "https://www.themeparkreview.com/forum/files/racer1_208.jpg",
    img4: "https://www.thirdstopontheright.com/wp-content/uploads/2019/02/ModernRacer-e1549413269341.jpg",
    date: new Date(Date.now())
  },
  {
    name: "Sky Rocket",
    park: "Kennywood",
    location: "West Mifflin, PA",
    operating: "June 29, 2010",
    type: "Steel",
    manufacturer: "Premier Rides",
    model: "Launch Coaster",
    height: 95,
    length: 2100,
    speed: 50,
    inversions: 3,
    duration: "1:05",
    vertangle: "90",
    gforce: "0.8",
    scale: "Extreme",
    awards: ["Top Steel Roller Coasters", "Best New Ride for 2010"],
    img1: "https://www.kennywood.com/sites/kennywood.com/files/kennywood_SkyRocket7.jpg",
    img2: "https://www.kennywood.com/sites/kennywood.com/files/kennywood_SkyRocket8.jpg",
    img3: "https://www.kennywood.com/sites/kennywood.com/files/kennywood_SkyRocket3.jpg",
    img4: "https://www.kennywood.com/sites/kennywood.com/files/kennywood_SkyRocket4.jpg",
    date: new Date(Date.now())
  },
  {
    name: "Steel Curtain",
    park: "Kennywood",
    location: "West Mifflin, PA",
    operating: "Summer 2019",
    type: "Steel",
    manufacturer: "S&S - Sansei Technologies",
    designer: "Joe Draves",
    height: 220,
    length: 4000,
    speed: 76,
    inversions: 9,
    duration: "2:00",
    vertangle: "90",
    gforce: "N/A",
    scale: "Extreme",
    awards: "",
    img1: "https://cdn.vox-cdn.com/thumbor/KNL6gQfXKwJdyNnl94tEwmQ4N4w=/0x0:6830x3530/1200x800/filters:focal(2390x1254:3482x2346)/cdn.vox-cdn.com/uploads/chorus_image/image/60446805/Steel_Curtain_full_coaster_2.0.png",
    img2: "https://i.ytimg.com/vi/CbsNYPm3pMU/maxresdefault.jpg",
    img3: "https://www.kennywood.com/sites/kennywood.com/files/GBP_4095%2020181102%200837%20S%26S%20Steeler%20Coaster_HDR.jpg",
    img4: "https://www.kennywood.com/sites/kennywood.com/files/GBP_4158%2020181102%200847%20S%26S%20Steeler%20Coaster_HDR.jpg",
    date: new Date(Date.now())
  }
];

db.Coaster
  .remove({})
  .then(() => db.Coaster.collection.insertMany(coasterSeed))
  .then(data => {
    console.log(data.result.n + " records inserted!");
    process.exit(0);
  })
  .catch(err => {
    console.error(err);
    process.exit(1);
  });
